/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    MainHeader: typeof import('./src/components/layout/MainHeader.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    SearchTableBar: typeof import('./src/components/SearchTableBar.vue')['default']
  }
}
